### PR TITLE
Optimize struct sizes

### PR DESCRIPTION
**Pull request by f2404**
Optimize struct sizes in memory by reordering their members.

### CODE REVIEW

**Comment by TimothyGu** [comment]
This breaks ABI.

**Comment by MarcusJohnson91** [comment]
DCADec hasn't been declared stable, so who cares?

**Comment by TimothyGu** [comment]
There has been a release, but if you guys are willing to break ABI this soon then ¯&#92;_(ツ)_/¯

**Comment by f2404** [comment]
Better to break it now than later :)

**Comment by Nevcairiel** [comment]
Don't really need to break at all just to save 4 bytes of memory, but in the end thats foo86's decisison.

**Comment by jamrial** [comment]
"Optimize struct dcadec_core_info size" requires a soname major bump since a release has been made, and for a four bytes gain it sounds pointless IMO.

The rest should be fine, i guess.

**Comment by foo86** [comment]
I'll reject this. Changing public structures like this is not allowed without breaking backwards compatibility. Overall, I prefer structure fields to be logically grouped as they are now, unless there is a noticeable benefit doing otherwise (saving just a few bytes of memory doesn't count).

**Pull request closed without merging**
