### PR TITLE
Makefile improvements

### PR DESCRIPTION
**Pull request by Underground78**
Here are some improvements for the Makefile which should make integrating dcadec in a complex build environment easier.

Makefiles are not my best suit at all so I'm open to suggestion and I will happily improve those patches.

### CODE REVIEW

**Comment by jamrial** [comment]
How does the out-of-tree stuff work in this case? make -fPATH_TO_MAKEFILE? Tried that and it only compiled one .c file.

Also, libinstall and decinstall sound weird. How about install-lib (or install-libdcadec) and install-dcadec, install-dcacut or similar?

**Comment by TimothyGu** [comment]
Why don't we just switch to automake? It'll make these stuff so much simpler.

**Comment by Nevcairiel** [comment]
> Also, libinstall and decinstall sound weird. How about install-lib (or install-libdcadec) and install-
> dcadec, install-dcacut or similar?

I agree, install-\* sounds better and is also what other Makefile projects seem to use more commonly

**Comment by Underground78** [comment]
> How does the out-of-tree stuff work in this case? make -fPATH_TO_MAKEFILE? Tried that and it only compiled one .c file.

Hmm, I just noticed that I `git stash`-ed  stuff and forgot to unstash so I was apparently trying normal compilation instead of out-of-tree... Sorry for that, I will test again properly and let you know.

> I agree, install-\* sounds better and is also what other Makefile projects seem to use more commonly

I wasn't sure about the `install` stuff, I will switch to `install-` with a suffix.

**Comment by Underground78** [comment]
As far as I can tell it works fine here. I'm testing with this build script: https://github.com/Underground78/mpc-hc/commit/4cd0bcb0aff46417cdec7692c4a50c2d965b52cd#diff-98304c44dcef09f5104c7062fc46d0eeR117.

I have repushed with the requested changes.

**Comment by Underground78** [comment]
I just found a mistake, I've repushed.

**Comment by foo86** [comment]
> I just found a mistake, I've repushed.

This still doesn't seem to work, just compiles a single file:

```
$ make 
mkdir -p libdcadec
cc -std=gnu99 -D_FILE_OFFSET_BITS=64 -Wall -Wextra -O3 -ffast-math -g -MMD    -c -o libdcadec/bitstream.o libdcadec/bitstream.c
$
```

I think new targets should be added after default target to make it work. Also, install-dec target contains whitespace error.

> Why don't we just switch to automake? It'll make these stuff so much simpler.

Well, maybe it is time to switch to some automatic build system, considering there are some expected features missing from the current Makefile (out of tree compilation, proper library versioning, SONAME, etc). I haven't used autotools in my projects before, and from my experience with autotools from a user point of view I hate it somewhat for being slow and unnecessarily complex. But if someone provides a reasonable patch to add autotools (or some other popular build system like cmake) support I might consider switching to it.

**Comment by TimothyGu** [comment]
> Well, maybe it is time to switch to some automatic build system, considering there are some expected features missing from the current Makefile (out of tree compilation, proper library versioning, SONAME, etc).

autotools supports all those. Better yet, it is standardized with many other projects so distribution integration would be very easy.

> I haven't used autotools in my projects before, and from my experience with autotools from a user point of view I hate it somewhat for being slow

It is kind of slow compared to "modern" alternatives but it is battle-tested.

> and unnecessarily complex.

The generated makefiles are complex, so is the generated configure script, but the .ac and .am sources are, in my opinion, not.

> But if someone provides a reasonable patch to add autotools (or some other popular build system like cmake) support I might consider switching to it.

OK I'll see what I can do during the weekend. I am not a big fan of CMake though because it is hard to extend it.

**Comment by ghost** [comment]
autotools is still better than cmake in my opinion.

**Comment by Nevcairiel** [comment]
autotools is a bane on the opensource world and should be avoided, imho.

**Comment by TimothyGu** [comment]
@Nevcairiel what would you recommend?

**Comment by Underground78** [comment]
@foo86: My bad, I forgot to test with no explicit rule. I will repush in a few minutes.

**Comment by MarcusJohnson91** [comment]
Why not use CMake instead of autotools?

**Comment by Underground78** [comment]
I've repushed with the whitespace error fixed too.

**Comment by kasper93** [comment]
If cmake is something you consider using, I could finish my patch, so far it is simple as it gets. https://github.com/kasper93/dcadec/commit/a84ad0524994adb9fc3c2b670a53d9ef3c2be9f4

**Comment by foo86** [comment]
> I've repushed with the whitespace error fixed too.

Merged, thanks.

> If cmake is something you consider using, I could finish my patch, so far it is simple as it gets.

I'll try to evaluate how well CMake works. Right now I'm inclining toward autotools (that works best and is generally expected on *nix) in parallel with a existing Makefile for Windows systems.

**Pull request merged**
