### PR TITLE
Use defines instead of magic numbers for DCT calculations

### PR DESCRIPTION
**Pull request by f2404**
Plus minor optimizations (combining 2 loops into 1)

### CODE REVIEW

**Comment by foo86** [comment]
Merged with some changes (got rid of _DBL defines), thanks.

**Comment by f2404** [comment]
I didn't put half sizes as (SIZE / 2) intentionally - in order to prevent them from being calculated in runtime, on each loop cycle (i=0; i < SIZE / 2; i++).

**Comment by Nevcairiel** [comment]
The compiler will pre-compute such things (constant divisions), and not generate a division in the code.

**Comment by f2404** [comment]
Ok.

**Pull request closed without merging**
